/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTailoringRouteImport } from './routes/_authenticated/tailoring'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedPlacementsRouteImport } from './routes/_authenticated/placements'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedMatchingRouteImport } from './routes/_authenticated/matching'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedBenchRouteImport } from './routes/_authenticated/bench'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedArchitectureRouteImport } from './routes/_authenticated/architecture'
import { Route as AuthenticatedAccessRequestRouteImport } from './routes/_authenticated/access-request'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors.index'
import { Route as AuthenticatedSubmissionsIndexRouteImport } from './routes/_authenticated/submissions.index'
import { Route as AuthenticatedRequirementsIndexRouteImport } from './routes/_authenticated/requirements.index'
import { Route as AuthenticatedRecruitersIndexRouteImport } from './routes/_authenticated/recruiters.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates.index'
import { Route as AuthenticatedVendorsNewRouteImport } from './routes/_authenticated/vendors.new'
import { Route as AuthenticatedVendorsIdRouteImport } from './routes/_authenticated/vendors.$id'
import { Route as AuthenticatedTenantsNewRouteImport } from './routes/_authenticated/tenants.new'
import { Route as AuthenticatedSubmissionsNewRouteImport } from './routes/_authenticated/submissions.new'
import { Route as AuthenticatedSubmissionsDraftRouteImport } from './routes/_authenticated/submissions.draft'
import { Route as AuthenticatedSubmissionsBoardRouteImport } from './routes/_authenticated/submissions.board'
import { Route as AuthenticatedSubmissionsIdRouteImport } from './routes/_authenticated/submissions.$id'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedRequirementsNewRouteImport } from './routes/_authenticated/requirements.new'
import { Route as AuthenticatedRequirementsIdRouteImport } from './routes/_authenticated/requirements.$id'
import { Route as AuthenticatedRecruitersIdRouteImport } from './routes/_authenticated/recruiters.$id'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedCandidatesNewRouteImport } from './routes/_authenticated/candidates.new'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as AuthenticatedBenchIdRouteImport } from './routes/_authenticated/bench.$id'
import { Route as AuthenticatedRequirementsIdEditRouteImport } from './routes/_authenticated/requirements.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTailoringRoute = AuthenticatedTailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementsRoute = AuthenticatedPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchingRoute = AuthenticatedMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenchRoute = AuthenticatedBenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchitectureRoute =
  AuthenticatedArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessRequestRoute =
  AuthenticatedAccessRequestRouteImport.update({
    id: '/access-request',
    path: '/access-request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsIndexRoute =
  AuthenticatedSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequirementsIndexRoute =
  AuthenticatedRequirementsIndexRouteImport.update({
    id: '/requirements/',
    path: '/requirements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruitersIndexRoute =
  AuthenticatedRecruitersIndexRouteImport.update({
    id: '/recruiters/',
    path: '/recruiters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsNewRoute = AuthenticatedVendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsIdRoute = AuthenticatedVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsNewRoute = AuthenticatedTenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsNewRoute =
  AuthenticatedSubmissionsNewRouteImport.update({
    id: '/submissions/new',
    path: '/submissions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsDraftRoute =
  AuthenticatedSubmissionsDraftRouteImport.update({
    id: '/submissions/draft',
    path: '/submissions/draft',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsBoardRoute =
  AuthenticatedSubmissionsBoardRouteImport.update({
    id: '/submissions/board',
    path: '/submissions/board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsIdRoute =
  AuthenticatedSubmissionsIdRouteImport.update({
    id: '/submissions/$id',
    path: '/submissions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequirementsNewRoute =
  AuthenticatedRequirementsNewRouteImport.update({
    id: '/requirements/new',
    path: '/requirements/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequirementsIdRoute =
  AuthenticatedRequirementsIdRouteImport.update({
    id: '/requirements/$id',
    path: '/requirements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruitersIdRoute =
  AuthenticatedRecruitersIdRouteImport.update({
    id: '/recruiters/$id',
    path: '/recruiters/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesNewRoute =
  AuthenticatedCandidatesNewRouteImport.update({
    id: '/candidates/new',
    path: '/candidates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBenchIdRoute = AuthenticatedBenchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBenchRoute,
} as any)
const AuthenticatedRequirementsIdEditRoute =
  AuthenticatedRequirementsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRequirementsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/access-request': typeof AuthenticatedAccessRequestRoute
  '/architecture': typeof AuthenticatedArchitectureRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/bench': typeof AuthenticatedBenchRouteWithChildren
  '/company': typeof AuthenticatedCompanyRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/matching': typeof AuthenticatedMatchingRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/tailoring': typeof AuthenticatedTailoringRoute
  '/users': typeof AuthenticatedUsersRoute
  '/bench/$id': typeof AuthenticatedBenchIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/recruiters/$id': typeof AuthenticatedRecruitersIdRoute
  '/requirements/$id': typeof AuthenticatedRequirementsIdRouteWithChildren
  '/requirements/new': typeof AuthenticatedRequirementsNewRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/submissions/board': typeof AuthenticatedSubmissionsBoardRoute
  '/submissions/draft': typeof AuthenticatedSubmissionsDraftRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/vendors/new': typeof AuthenticatedVendorsNewRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/recruiters/': typeof AuthenticatedRecruitersIndexRoute
  '/requirements/': typeof AuthenticatedRequirementsIndexRoute
  '/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/requirements/$id/edit': typeof AuthenticatedRequirementsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/access-request': typeof AuthenticatedAccessRequestRoute
  '/architecture': typeof AuthenticatedArchitectureRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/bench': typeof AuthenticatedBenchRouteWithChildren
  '/company': typeof AuthenticatedCompanyRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/matching': typeof AuthenticatedMatchingRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/tailoring': typeof AuthenticatedTailoringRoute
  '/users': typeof AuthenticatedUsersRoute
  '/bench/$id': typeof AuthenticatedBenchIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/recruiters/$id': typeof AuthenticatedRecruitersIdRoute
  '/requirements/$id': typeof AuthenticatedRequirementsIdRouteWithChildren
  '/requirements/new': typeof AuthenticatedRequirementsNewRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/submissions/board': typeof AuthenticatedSubmissionsBoardRoute
  '/submissions/draft': typeof AuthenticatedSubmissionsDraftRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/vendors/new': typeof AuthenticatedVendorsNewRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/recruiters': typeof AuthenticatedRecruitersIndexRoute
  '/requirements': typeof AuthenticatedRequirementsIndexRoute
  '/submissions': typeof AuthenticatedSubmissionsIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/requirements/$id/edit': typeof AuthenticatedRequirementsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/access-request': typeof AuthenticatedAccessRequestRoute
  '/_authenticated/architecture': typeof AuthenticatedArchitectureRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/bench': typeof AuthenticatedBenchRouteWithChildren
  '/_authenticated/company': typeof AuthenticatedCompanyRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/matching': typeof AuthenticatedMatchingRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/placements': typeof AuthenticatedPlacementsRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/tailoring': typeof AuthenticatedTailoringRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/bench/$id': typeof AuthenticatedBenchIdRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/recruiters/$id': typeof AuthenticatedRecruitersIdRoute
  '/_authenticated/requirements/$id': typeof AuthenticatedRequirementsIdRouteWithChildren
  '/_authenticated/requirements/new': typeof AuthenticatedRequirementsNewRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/_authenticated/submissions/board': typeof AuthenticatedSubmissionsBoardRoute
  '/_authenticated/submissions/draft': typeof AuthenticatedSubmissionsDraftRoute
  '/_authenticated/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/_authenticated/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/_authenticated/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/_authenticated/vendors/new': typeof AuthenticatedVendorsNewRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/recruiters/': typeof AuthenticatedRecruitersIndexRoute
  '/_authenticated/requirements/': typeof AuthenticatedRequirementsIndexRoute
  '/_authenticated/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/requirements/$id/edit': typeof AuthenticatedRequirementsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/access-request'
    | '/architecture'
    | '/audit'
    | '/bench'
    | '/company'
    | '/copilot'
    | '/dashboard'
    | '/developer'
    | '/forbidden'
    | '/interviews'
    | '/matching'
    | '/overview'
    | '/placements'
    | '/platform'
    | '/tailoring'
    | '/users'
    | '/bench/$id'
    | '/candidates/$id'
    | '/candidates/new'
    | '/clients/$id'
    | '/clients/new'
    | '/recruiters/$id'
    | '/requirements/$id'
    | '/requirements/new'
    | '/settings/profile'
    | '/submissions/$id'
    | '/submissions/board'
    | '/submissions/draft'
    | '/submissions/new'
    | '/tenants/new'
    | '/vendors/$id'
    | '/vendors/new'
    | '/candidates/'
    | '/clients/'
    | '/recruiters/'
    | '/requirements/'
    | '/submissions/'
    | '/vendors/'
    | '/requirements/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/access-request'
    | '/architecture'
    | '/audit'
    | '/bench'
    | '/company'
    | '/copilot'
    | '/dashboard'
    | '/developer'
    | '/forbidden'
    | '/interviews'
    | '/matching'
    | '/overview'
    | '/placements'
    | '/platform'
    | '/tailoring'
    | '/users'
    | '/bench/$id'
    | '/candidates/$id'
    | '/candidates/new'
    | '/clients/$id'
    | '/clients/new'
    | '/recruiters/$id'
    | '/requirements/$id'
    | '/requirements/new'
    | '/settings/profile'
    | '/submissions/$id'
    | '/submissions/board'
    | '/submissions/draft'
    | '/submissions/new'
    | '/tenants/new'
    | '/vendors/$id'
    | '/vendors/new'
    | '/candidates'
    | '/clients'
    | '/recruiters'
    | '/requirements'
    | '/submissions'
    | '/vendors'
    | '/requirements/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/access-request'
    | '/_authenticated/architecture'
    | '/_authenticated/audit'
    | '/_authenticated/bench'
    | '/_authenticated/company'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer'
    | '/_authenticated/forbidden'
    | '/_authenticated/interviews'
    | '/_authenticated/matching'
    | '/_authenticated/overview'
    | '/_authenticated/placements'
    | '/_authenticated/platform'
    | '/_authenticated/tailoring'
    | '/_authenticated/users'
    | '/_authenticated/bench/$id'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/candidates/new'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/recruiters/$id'
    | '/_authenticated/requirements/$id'
    | '/_authenticated/requirements/new'
    | '/_authenticated/settings/profile'
    | '/_authenticated/submissions/$id'
    | '/_authenticated/submissions/board'
    | '/_authenticated/submissions/draft'
    | '/_authenticated/submissions/new'
    | '/_authenticated/tenants/new'
    | '/_authenticated/vendors/$id'
    | '/_authenticated/vendors/new'
    | '/_authenticated/candidates/'
    | '/_authenticated/clients/'
    | '/_authenticated/recruiters/'
    | '/_authenticated/requirements/'
    | '/_authenticated/submissions/'
    | '/_authenticated/vendors/'
    | '/_authenticated/requirements/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tailoring': {
      id: '/_authenticated/tailoring'
      path: '/tailoring'
      fullPath: '/tailoring'
      preLoaderRoute: typeof AuthenticatedTailoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placements': {
      id: '/_authenticated/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof AuthenticatedPlacementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matching': {
      id: '/_authenticated/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AuthenticatedMatchingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bench': {
      id: '/_authenticated/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof AuthenticatedBenchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/architecture': {
      id: '/_authenticated/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AuthenticatedArchitectureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-request': {
      id: '/_authenticated/access-request'
      path: '/access-request'
      fullPath: '/access-request'
      preLoaderRoute: typeof AuthenticatedAccessRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/': {
      id: '/_authenticated/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AuthenticatedSubmissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requirements/': {
      id: '/_authenticated/requirements/'
      path: '/requirements'
      fullPath: '/requirements/'
      preLoaderRoute: typeof AuthenticatedRequirementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiters/': {
      id: '/_authenticated/recruiters/'
      path: '/recruiters'
      fullPath: '/recruiters/'
      preLoaderRoute: typeof AuthenticatedRecruitersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/new': {
      id: '/_authenticated/vendors/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof AuthenticatedVendorsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$id': {
      id: '/_authenticated/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AuthenticatedVendorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/new': {
      id: '/_authenticated/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof AuthenticatedTenantsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/new': {
      id: '/_authenticated/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof AuthenticatedSubmissionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/draft': {
      id: '/_authenticated/submissions/draft'
      path: '/submissions/draft'
      fullPath: '/submissions/draft'
      preLoaderRoute: typeof AuthenticatedSubmissionsDraftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/board': {
      id: '/_authenticated/submissions/board'
      path: '/submissions/board'
      fullPath: '/submissions/board'
      preLoaderRoute: typeof AuthenticatedSubmissionsBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/$id': {
      id: '/_authenticated/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AuthenticatedSubmissionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requirements/new': {
      id: '/_authenticated/requirements/new'
      path: '/requirements/new'
      fullPath: '/requirements/new'
      preLoaderRoute: typeof AuthenticatedRequirementsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requirements/$id': {
      id: '/_authenticated/requirements/$id'
      path: '/requirements/$id'
      fullPath: '/requirements/$id'
      preLoaderRoute: typeof AuthenticatedRequirementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiters/$id': {
      id: '/_authenticated/recruiters/$id'
      path: '/recruiters/$id'
      fullPath: '/recruiters/$id'
      preLoaderRoute: typeof AuthenticatedRecruitersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/new': {
      id: '/_authenticated/candidates/new'
      path: '/candidates/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof AuthenticatedCandidatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bench/$id': {
      id: '/_authenticated/bench/$id'
      path: '/$id'
      fullPath: '/bench/$id'
      preLoaderRoute: typeof AuthenticatedBenchIdRouteImport
      parentRoute: typeof AuthenticatedBenchRoute
    }
    '/_authenticated/requirements/$id/edit': {
      id: '/_authenticated/requirements/$id/edit'
      path: '/edit'
      fullPath: '/requirements/$id/edit'
      preLoaderRoute: typeof AuthenticatedRequirementsIdEditRouteImport
      parentRoute: typeof AuthenticatedRequirementsIdRoute
    }
  }
}

interface AuthenticatedBenchRouteChildren {
  AuthenticatedBenchIdRoute: typeof AuthenticatedBenchIdRoute
}

const AuthenticatedBenchRouteChildren: AuthenticatedBenchRouteChildren = {
  AuthenticatedBenchIdRoute: AuthenticatedBenchIdRoute,
}

const AuthenticatedBenchRouteWithChildren =
  AuthenticatedBenchRoute._addFileChildren(AuthenticatedBenchRouteChildren)

interface AuthenticatedRequirementsIdRouteChildren {
  AuthenticatedRequirementsIdEditRoute: typeof AuthenticatedRequirementsIdEditRoute
}

const AuthenticatedRequirementsIdRouteChildren: AuthenticatedRequirementsIdRouteChildren =
  {
    AuthenticatedRequirementsIdEditRoute: AuthenticatedRequirementsIdEditRoute,
  }

const AuthenticatedRequirementsIdRouteWithChildren =
  AuthenticatedRequirementsIdRoute._addFileChildren(
    AuthenticatedRequirementsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessRequestRoute: typeof AuthenticatedAccessRequestRoute
  AuthenticatedArchitectureRoute: typeof AuthenticatedArchitectureRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBenchRoute: typeof AuthenticatedBenchRouteWithChildren
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedMatchingRoute: typeof AuthenticatedMatchingRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPlacementsRoute: typeof AuthenticatedPlacementsRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedTailoringRoute: typeof AuthenticatedTailoringRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
  AuthenticatedCandidatesNewRoute: typeof AuthenticatedCandidatesNewRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedRecruitersIdRoute: typeof AuthenticatedRecruitersIdRoute
  AuthenticatedRequirementsIdRoute: typeof AuthenticatedRequirementsIdRouteWithChildren
  AuthenticatedRequirementsNewRoute: typeof AuthenticatedRequirementsNewRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSubmissionsIdRoute: typeof AuthenticatedSubmissionsIdRoute
  AuthenticatedSubmissionsBoardRoute: typeof AuthenticatedSubmissionsBoardRoute
  AuthenticatedSubmissionsDraftRoute: typeof AuthenticatedSubmissionsDraftRoute
  AuthenticatedSubmissionsNewRoute: typeof AuthenticatedSubmissionsNewRoute
  AuthenticatedTenantsNewRoute: typeof AuthenticatedTenantsNewRoute
  AuthenticatedVendorsIdRoute: typeof AuthenticatedVendorsIdRoute
  AuthenticatedVendorsNewRoute: typeof AuthenticatedVendorsNewRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedRecruitersIndexRoute: typeof AuthenticatedRecruitersIndexRoute
  AuthenticatedRequirementsIndexRoute: typeof AuthenticatedRequirementsIndexRoute
  AuthenticatedSubmissionsIndexRoute: typeof AuthenticatedSubmissionsIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessRequestRoute: AuthenticatedAccessRequestRoute,
  AuthenticatedArchitectureRoute: AuthenticatedArchitectureRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBenchRoute: AuthenticatedBenchRouteWithChildren,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedMatchingRoute: AuthenticatedMatchingRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPlacementsRoute: AuthenticatedPlacementsRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedTailoringRoute: AuthenticatedTailoringRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  AuthenticatedCandidatesNewRoute: AuthenticatedCandidatesNewRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedRecruitersIdRoute: AuthenticatedRecruitersIdRoute,
  AuthenticatedRequirementsIdRoute:
    AuthenticatedRequirementsIdRouteWithChildren,
  AuthenticatedRequirementsNewRoute: AuthenticatedRequirementsNewRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSubmissionsIdRoute: AuthenticatedSubmissionsIdRoute,
  AuthenticatedSubmissionsBoardRoute: AuthenticatedSubmissionsBoardRoute,
  AuthenticatedSubmissionsDraftRoute: AuthenticatedSubmissionsDraftRoute,
  AuthenticatedSubmissionsNewRoute: AuthenticatedSubmissionsNewRoute,
  AuthenticatedTenantsNewRoute: AuthenticatedTenantsNewRoute,
  AuthenticatedVendorsIdRoute: AuthenticatedVendorsIdRoute,
  AuthenticatedVendorsNewRoute: AuthenticatedVendorsNewRoute,
  AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedRecruitersIndexRoute: AuthenticatedRecruitersIndexRoute,
  AuthenticatedRequirementsIndexRoute: AuthenticatedRequirementsIndexRoute,
  AuthenticatedSubmissionsIndexRoute: AuthenticatedSubmissionsIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
