// This file is generated by the Supabase/Lovable integration.
// Do not add application-specific authentication or authorization logic here.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { assertPublishableSupabaseKey, isOpaquePublishableKey } from "./api-key-safety";

/**
 * Determines whether a Supabase API key uses the newer key format.
 *
 * New public Supabase keys look like sb_publishable_...
 *
 * Older Supabase anon keys are JWT-shaped strings.
 */
/**
 * Ensures the Supabase API key is sent through the `apikey` header.
 *
 * The API key is NOT the user's authentication token.
 *
 * The user's authenticated session/access token is managed separately
 * by Supabase Auth.
 */
function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    /**
     * Merge headers supplied by the caller.
     */
    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => {
        headers.set(key, value);
      });
    }

    /**
     * New Supabase API keys are opaque values and must not
     * accidentally be used as Bearer authentication tokens.
     */
    if (
      isOpaquePublishableKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    /**
     * Supabase API key.
     *
     * This is safe to expose when it is the publishable/anon key.
     * It is NOT a service-role/secret key.
     */
    headers.set("apikey", supabaseKey);

    return fetch(input, {
      ...init,
      headers,
    });
  };
}

/**
 * Read the Supabase configuration.
 *
 * Browser:
 *   VITE_SUPABASE_URL
 *   VITE_SUPABASE_PUBLISHABLE_KEY
 *
 * SSR/server:
 *   SUPABASE_URL
 *   SUPABASE_PUBLISHABLE_KEY
 *
 * IMPORTANT:
 * Never use a service-role/secret key here.
 */
function getSupabaseConfig(): {
  url: string;
  publishableKey: string;
} {
  const url = import.meta.env.VITE_SUPABASE_URL ?? process.env.SUPABASE_URL;

  const publishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;

  const missing: string[] = [];

  if (!url) {
    missing.push("VITE_SUPABASE_URL");
  }

  if (!publishableKey) {
    missing.push("VITE_SUPABASE_PUBLISHABLE_KEY");
  }

  if (missing.length > 0) {
    const message = `Missing Supabase environment variable(s): ` + `${missing.join(", ")}.`;

    console.error(`[Supabase] ${message}`);

    throw new Error(message);
  }

  assertPublishableSupabaseKey(publishableKey);

  return {
    url,
    publishableKey,
  };
}

/**
 * Create the typed Supabase client.
 *
 * This client:
 *
 * - knows the Supabase project
 * - manages the user's Supabase Auth session
 * - automatically refreshes the session
 * - persists the session in the browser
 * - provides typed database access through Database
 *
 * It does NOT decide whether a user is an admin/recruiter/etc.
 */
function createSupabaseClient() {
  const { url, publishableKey } = getSupabaseConfig();

  return createClient<Database>(url, publishableKey, {
    global: {
      fetch: createSupabaseFetch(publishableKey),
    },

    auth: {
      /**
       * Browser:
       *
       * Persist the Supabase Auth session so a page refresh
       * does not immediately log the user out.
       *
       * Server:
       *
       * There is no browser localStorage, so storage is undefined.
       */
      storage: typeof window !== "undefined" ? window.localStorage : undefined,

      /**
       * Keep the authenticated session available across
       * browser page loads.
       */
      persistSession: true,

      /**
       * Automatically refresh an expiring Supabase session
       * in the browser.
       */
      autoRefreshToken: true,

      /**
       * Allow Supabase to process OAuth callback information
       * in the browser URL.
       */
      detectSessionInUrl: typeof window !== "undefined",
    },
  });
}

/**
 * Lazily-created singleton.
 *
 * Lazy initialization prevents environment configuration from being
 * evaluated until the Supabase client is actually used.
 */
let supabaseClient: ReturnType<typeof createSupabaseClient> | undefined;

/**
 * Public typed Supabase client.
 *
 * Usage:
 *
 *   import { supabase } from "@/integrations/supabase/client";
 *
 * Example:
 *
 *   const {
 *     data: { user },
 *   } = await supabase.auth.getUser();
 */
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, property, receiver) {
    if (!supabaseClient) {
      supabaseClient = createSupabaseClient();
    }

    return Reflect.get(supabaseClient, property, receiver);
  },
});
